### PR TITLE
Update security policy for GitHub private vulnerability reporting

### PR DESCRIPTION
**Pull request by br3ndonland**
## Description

We've taken a couple of stabs at making a security policy. Currently it is stored in encode/.github, to apply to the whole organization, and looks like this:

Current Encode security policy

To improve on this, could we consider using GitHub's new [private vulnerability reporting](https://github.blog/changelog/2022-11-09-privately-report-vulnerabilities-to-repository-maintainers/) feature? Users reporting vulnerabilities navigate to the Security tab for the repo and click "Report a vulnerability."

See the [github-demos/private-vulnerability-reporting](https://github.com/github-demos/private-vulnerability-reporting/security) repo for an example of how this looks.

### This PR

This PR will add text to the security policy describing the procedure.

### TODO for @encode/operations

In order to [enable private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository), a member of @encode/operations can navigate to Settings -> Code Security, and enable the private vulnerability reporting beta for each repo.

Screenshot from GitHub docs showing how to enable private vulnerability reporting

## Related

- encode/starlette#1862
- encode/.github#1
- [GitHub docs: Security - Security advisories - Configure private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)
- [github-demos/private-vulnerability-reporting](https://github.com/github-demos/private-vulnerability-reporting/security)

### CODE REVIEW

**Comment by Kludex** [comment]
Something missing here for it to be a draft?

I'm happy with this idea :)

cc @tomchristie

**Comment by tomchristie** [comment]
Neat. I've just enabled this for `httpx`, `uvicorn`, and `starlette`.

**Review by Kludex — APPROVED** [review]

**Comment by Kludex** [comment]
It can't reference a local image :sweat_smile: 

image

cc @tomchristie :eyes:

**Comment by lovelydinosaur** [comment]
@Kludex Sorted it, thanks...

https://github.com/encode/.github/pull/3

**Pull request merged**
